https:
  host: "0.0.0.0"
  port: "8082"
  private:
    port: "8092"

api:
  id: ""
  flow: "mule-archetype-app-main"

keystore:
  password: "![LAM0s+J7Jf6Un36fQi271g==]" #Key: passkey, Algorithm: Blowfish, State: CBC
  key:
    password: "![LAM0s+J7Jf6Un36fQi271g==]" #Key: passkey, Algorithm: Blowfish, State: CBC
  path: "keystore.jks"
  alias: "mule"

msg: "Welcome to the ArcheType Template Project"